### ISSUE TITLE
Ændringer til Sophus Claussens "Djævlerier"

### ISSUE THREAD

**Issue by Musagetes** [thabz/Kalliope#619]
- [x] Citatet til "Brev fra Landet" er af Gottfried August Bürger, og kan findes øverst på denne side, "Die Esel und die Nachtigallen": https://books.google.dk/books?id=UW86AAAAcAAJ&pg=PA285&lpg=PA285&dq=b%C3%BCrger+nachtigall+gedicht&source=bl&ots=pBVKFYWFnX&sig=ACfU3U0WTXyH5D_9iyZQS_1bb-htXDwpCw&hl=en&sa=X&ved=2ahUKEwjqv_W6j8fgAhVMY1AKHaWcCy8Q6AEwBnoECAgQAQ#v=onepage&q=b%C3%BCrger%20nachtigall%20gedicht&f=false

- [x] "Trappen til Helvede" er en sektion, og de syv digte deri burde deles op til individuelle digte: https://kalliope.org/da/text/claussen2001122318

- [x] I førsteudgaven hører digtene "Fanfare" og "Mødet" sammen, jeg tænker, de skal flettes sammen til et enkelt digt.

- [x] Kan citatet til sektionen _Afrodites Dampe_, der forøvrigt bør deles op i individuelle digte med romertalsnummerering, være følgende Heine-digt, til trods for at ordlyden ikke er den samme, og at Claussen måske bare husker forkert?
![screenshot 2019-02-19 16 28 04](https://user-images.githubusercontent.com/35627700/53026726-bedbe700-3463-11e9-82a9-208ec20ca770.png)
(https://books.google.dk/books?id=0hZKAAAAIAAJ&pg=RA2-PA160&lpg=RA2-PA160&dq=Ihr+seid+eine+Teufelinne+heine&source=bl&ots=189OXT1uBe&sig=ACfU3U2R_KgaRbm9vuuEHmD1bRuCu6eBng&hl=en&sa=X&ved=2ahUKEwi8pfy1n8jgAhVF6KQKHacIC1EQ6AEwAXoECAkQAQ#v=onepage&q=Ihr%20seid%20eine%20Teufelinne%20heine&f=false)

**Comment by thabz** [comment]
**Die Esel und die Nachtigallen** 

Es gibt der Esel welche wollen 
Daß Nachtigallen hin und her.
Des Müllers Säcke tragen sollen.
Ob's recht? fällt mir zu sagen schwer.
Das weiß ich: Nachtigallen wollen 
Nicht, daß die Esel singen sollen

![skaermbillede 2019-02-19 kl 08 49 27](https://user-images.githubusercontent.com/157777/52998340-579e4280-3423-11e9-8d9b-da20831c5fba.png)

**Comment by thabz** [comment]
@Musagetes mottoet med Teufelinne stammer fra en eller anden udgave den tyske middelalderballade »Der Tannhaüser«. Heine har bare lavet en variant.
