### ISSUE TITLE
Ændringer til Rimestads "De høstlige Hymner"

### ISSUE THREAD

**Issue by Musagetes** [thabz/Kalliope#647]
- [x] Vers 18 i https://kalliope.org/da/text/rimestad2019030713 har et foranstillet "V", der ikke skal være der.

- [x] Til sektionen _En Elegi_ kan der sættes `<keywords>elegi</keywords>`, da Rimestad selv kalder sektionen det, og tonen i digtene er af elegisk stemning.
 
- [x] Vers 33 i https://kalliope.org/da/text/rimestad2019030703 har en sær apostrof. Skal den være der, eller er det noget smuds i faksimilen?
 
- [x] `<keywords>kuplet</keywords>` til https://kalliope.org/da/text/rimestad2019030707

**Comment by thabz** [comment]
Tak! Fikset.
