### ISSUE TITLE
Ændringer til Kristian Arentzen: "Digtsamling" (1862)

### ISSUE THREAD

**Issue by Musagetes** [thabz/Kalliope#670]
_Synderinden_ (https://kalliope.org/da/text/arentzen2019010601) kan der sættes <keywords>kuplet</keywords> ved. (Sammesteds kan der ditto: https://kalliope.org/da/text/arentzen2019011293)

_Grisetten_ (https://kalliope.org/da/text/arentzen2019010605) ligeledes <keywords>kuplet</kuplet> (og https://kalliope.org/da/text/arentzen2019011241)

_Haandværkersang_ (https://kalliope.org/da/text/arentzen2019010612), sidste vers: Læst] Læft (kan bl.a. ses på rimet med "bedst"). (https://kalliope.org/da/text/arentzen2019011266 ligeledes.)

_Ved Sygehjemmets Indvielse_ (https://kalliope.org/da/text/arentzen2019010663), vers 15: underfuld] undersuld.

**Comment by thabz** [comment]
Fikset med 7261f1fc08db3a6e5ae57b4ba99282d13a39fd62.
