### ISSUE TITLE
Ændringer til Rasmus Frankenau: Nytaarsgave for 1815 (1815)

### ISSUE THREAD

**Issue by Musagetes** [thabz/Kalliope#698]
_Linas, en Landsbyeskiønheds Sang_ (https://kalliope.org/da/text/frankenau2019041221): OCR-fejl: Besøg] Bessg

Følgende digte kan der med fordel sættes `<keywords>drikkevise</keywords>` ved:

- _Velkomstsang_ (https://kalliope.org/da/text/frankenau2019041262)
- _Afskedssang_ (https://kalliope.org/da/text/frankenau2019041263)
- _Til Venskabs Fest, som hvert et Hierte fryder_ (https://kalliope.org/da/text/frankenau2019041265)
- _Et Samfunds Aar er atter lagt tilbage_ (https://kalliope.org/da/text/frankenau2019041266)
- _Lystig min Broder! og lystig igien!_ (https://kalliope.org/da/text/frankenau2001070309)
- _Høstsang_ (https://kalliope.org/da/text/frankenau2019041210)
- _Det skummende Bæger begynde sin Gang_ (https://kalliope.org/da/text/frankenau2001053004)
- _Hver Glædens Ven_ (https://kalliope.org/da/text/frankenau2019041270)
- _Lad Mennesker dræbes, og Riger forgaae_ (https://kalliope.org/da/text/frankenau2001070307)
- _Langt meer end Guld er Druen værd_ (https://kalliope.org/da/text/frankenau2001070308)
- _Samles hid til Venskabs Kiæde_ (https://kalliope.org/da/text/frankenau2019041273)
- _Høit leve, hvo ved Bægerklang_ (https://kalliope.org/da/text/frankenau2001060302)
- _Fyld Glasset, Ven, og kom ihu_ (https://kalliope.org/da/text/frankenau2019041275)
- _Velkommen enhver, som har Druesaft kier_ (https://kalliope.org/da/text/frankenau2001070320)
- _Snart er din Ungdomstid forsvunden_ (https://kalliope.org/da/text/frankenau2001070313)
- _Vaarsang_ (https://kalliope.org/da/text/frankenau2019041280)
- _Vintersang i Maaneskin_ (https://kalliope.org/da/text/frankenau2019041281)
- _Selskabssang_ (https://kalliope.org/da/text/frankenau2001070316)
- _Balsang_ (https://kalliope.org/da/text/frankenau2019041283)
- _Maskeradesang_ (https://kalliope.org/da/text/frankenau2019041284)
- _Vaarsang_ (https://kalliope.org/da/text/frankenau2019041285)
- _Vaarsang_ (https://kalliope.org/da/text/frankenau2019041286)

**Comment by thabz** [comment]
Tak, @Musagetes!
