### ISSUE TITLE
Baggesens »Jeppe« og »Emma« skal have egne id'er

### ISSUE THREAD

**Issue by thabz** [thabz/Kalliope#724]
Giv »Jeppe« og »Emma« i Eventyrer og comiske Fortællinger (1807) egne id'er, så vi kan angive dem som varianter i deres ditto i Ungdomsarbeider.

**Comment by Musagetes** [comment]
Se: https://kalliope.org/da/text/baggesen2018101601 og https://kalliope.org/da/text/baggesen2019080360 , så smukt!

**Comment by thabz** [comment]
Jaja, det er ikke tosset. :-)

**Comment by thabz** [comment]
Wow. Min åndssvage kommentar ovenfor, skete ved at jeg svarede på advis-mailen GitHub sendte til mig, pga. din kommentar.

**Comment by Musagetes** [comment]
For at citere en vismand:
“Sateme smart” er hvad vi stiler efter.

On Sat, Aug 24, 2019 at 1:13 PM Jesper Christensen <notifications@github.com>
wrote:
>
> Wow. Min åndssvage kommentar ovenfor, skete ved at jeg svarede på
advis-mailen GitHub sendte til mig, pga. din kommentar.

**Comment by thabz** [comment]
Fikset med 83403e394.
