### ISSUE TITLE
A. Munchs oversættelse af Tennysons Enoch Arden

### ISSUE THREAD

**Issue by thabz** [thabz/Kalliope#785]
http://www.kb.dk/e-mat/dod/11540804869D.pdf

**Comment by Musagetes** [comment]
Den ligger klar som råtekst: https://github.com/thabz/Kalliope/pull/787

**Comment by thabz** [comment]
Og Tennysons førsteudgave som faksimile , hvis det falder over os: 

https://archive.org/details/enochardenetcby00tenngoog/page/n12

**Comment by Musagetes** [comment]
Og teksten her: http://www.everypoet.com/archive/poetry/Tennyson/tennyson_contents_enoch_arden.htm
